import type { CalculatorButton } from '../model';

export const calculatorButtons: CalculatorButton[] = [
	{ label: 'ON/C', type: 'operator' },
	{ label: 'OFF', type: 'operator' },
	{ label: '%', type: 'operator' },
	{ label: '←', type: 'operator' },
	{ label: '7', type: 'digit' },
	{ label: '8', type: 'digit' },
	{ label: '9', type: 'digit' },
	{ label: '÷', type: 'operator' },
	{ label: '4', type: 'digit' },
	{ label: '5', type: 'digit' },
	{ label: '6', type: 'digit' },
	{ label: '×', type: 'operator' },
	{ label: '1', type: 'digit' },
	{ label: '2', type: 'digit' },
	{ label: '3', type: 'digit' },
	{ label: '-', type: 'operator' },
	{ label: '±', type: 'operator' },
	{ label: '0', type: 'digit' },
	{ label: '.', type: 'operator' },
	{ label: '+', type: 'operator' },
	{ label: '(', type: 'operator', colSpan: 1 },
	{ label: ')', type: 'operator', colSpan: 1 },
	{ label: '=', type: 'result', colSpan: 2 },
];
