import { CalculatorButton } from '../model';

export const calculatorButtons: CalculatorButton[] = [
	{ label: 'ON/C' },
	{ label: 'OFF' },
	{ label: '√' },
	{ label: '⌫' },
	{ label: '7' },
	{ label: '8' },
	{ label: '9' },
	{ label: '÷' },
	{ label: '4' },
	{ label: '5' },
	{ label: '6' },
	{ label: '×' },
	{ label: '1' },
	{ label: '2' },
	{ label: '3' },
	{ label: '-' },
	{ label: '±' },
	{ label: '0' },
	{ label: '.' },
	{ label: '+' },
	{ label: '(', colSpan: 1 },
	{ label: ')', colSpan: 1 },
	{ label: '=', colSpan: 2 },
];
