export { AVATAR_OPTIONS } from './avatars';
export {
	DEFAULT_CITY,
	DEFAULT_USER_PROFILE,
	LAST_CITY_KEY,
	SESSION_EXPIRATION_MS,
	STORAGE_DELETED,
	STORAGE_DELETED_AT,
	STORAGE_KEY,
	STORAGE_TIMESTAMP_KEY,
	WEEKDAYS_RU_SHORT,
} from './constants';
export { SLIDER_CONTENT } from './slides';
