import type { Column, Task } from '../model';

export const getDefaultColumns = (): Omit<Column, 'id'>[] => [
	{ title: 'Запланировано', color: 'slate', taskLimit: 10, position: 0 },
	{ title: 'Подготовка', color: 'amber', taskLimit: 10, position: 1 },
	{ title: 'В работе', color: 'rose', taskLimit: 10, position: 2 },
	{ title: 'Завершено', color: 'lime', taskLimit: 10, position: 3 },
];

export const getDefaultTasks = (columnIds: string[]): Omit<Task, 'id'>[] => [
	{
		columnId: columnIds[0] ?? '',
		title: 'Составить план на неделю',
		description: 'Определи основные задачи на ближайшие дни, чтобы понимать объём работы.',
		status: 'waiting',
		priority: 'high',
		startDate: '2026-03-18',
		endDate: '2026-03-20',
		completed: false,
		position: 0,
		createdAt: '18.03.2026, 10:00',
	},
	{
		columnId: columnIds[1] ?? '',
		title: 'Подготовить материалы к совещанию',
		description: 'Собери документы, заметки и данные, которые понадобятся на встрече.',
		status: 'waiting',
		priority: 'medium',
		startDate: '2026-03-18',
		endDate: '2026-03-22',
		completed: false,
		position: 0,
		createdAt: '18.03.2026, 11:00',
	},
	{
		columnId: columnIds[1] ?? '',
		title: 'Уточнить информацию у коллег',
		description: 'Свяжись с ответственными сотрудниками и уточни недостающие детали по проекту.',
		status: 'waiting',
		priority: 'low',
		startDate: '2026-03-19',
		endDate: '2026-03-21',
		completed: false,
		position: 1,
		createdAt: '18.03.2026, 11:30',
	},
	{
		columnId: columnIds[2] ?? '',
		title: 'Подготовить шаблон документа',
		description: 'Сделай простой шаблон, которым смогут пользоваться коллеги.',
		status: 'waiting',
		priority: 'high',
		startDate: '2026-03-18',
		endDate: '2026-03-25',
		completed: false,
		position: 0,
		createdAt: '18.03.2026, 12:00',
	},
	{
		columnId: columnIds[3] ?? '',
		title: 'Проверить выполненные задачи',
		description: 'Убедись, что завершённые задачи действительно закрыты и всё оформлено корректно.',
		status: 'waiting',
		priority: 'low',
		startDate: '2026-03-18',
		endDate: '2026-03-18',
		completed: false,
		position: 0,
		createdAt: '18.03.2026, 13:00',
	},
	{
		columnId: columnIds[3] ?? '',
		title: 'Отправить отчёт руководителю',
		description: 'Собери краткое резюме по текущему прогрессу и отправь на почту.',
		status: 'waiting',
		priority: 'medium',
		startDate: '2026-03-18',
		endDate: '2026-03-19',
		completed: false,
		position: 1,
		createdAt: '18.03.2026, 13:30',
	},
];
